import type { CategoryInput, ProductInput, ReelInput, ReviewInput } from "@/lib/types/entities"

export const seedCategories: Array<CategoryInput & { id: string }> = [
  { id: "smartphones", name: "Smartphones", slug: "smartphones", image: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600&h=400&fit=crop", active: true, sortOrder: 1 },
  { id: "audio", name: "Audio", slug: "audio", image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&h=400&fit=crop", active: true, sortOrder: 2 },
  { id: "wearables", name: "Wearables", slug: "wearables", image: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&h=400&fit=crop", active: true, sortOrder: 3 },
]

export const seedProducts: Array<ProductInput & { id: string }> = [
  {
    id: "iphone-15-pro-max",
    title: "iPhone 15 Pro Max",
    slug: "iphone-15-pro-max",
    shortDescription: "A17 Pro flagship with titanium build.",
    fullDescription: "The iPhone 15 Pro Max combines premium titanium design, pro-grade cameras, and smooth everyday performance.",
    brand: "Apple",
    price: 1199,
    salePrice: 1099,
    categoryId: "smartphones",
    images: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&h=800&fit=crop"],
    highlights: ["A17 Pro chip", "48MP camera", "Titanium design"],
    specifications: [
      { label: "Display", value: "6.7-inch OLED" },
      { label: "Battery", value: "All-day battery life" },
      { label: "Storage", value: "256GB" },
    ],
    colors: ["Natural Titanium", "Black Titanium"],
    storageOptions: ["256GB", "512GB"],
    rating: 4.9,
    reviewCount: 320,
    featured: true,
    active: true,
    stockStatus: "in_stock",
  },
  {
    id: "galaxy-s24-ultra",
    title: "Galaxy S24 Ultra",
    slug: "galaxy-s24-ultra",
    shortDescription: "AI flagship with 200MP camera.",
    fullDescription: "Galaxy S24 Ultra is built for power users with strong camera hardware, S Pen support, and flagship performance.",
    brand: "Samsung",
    price: 1099,
    salePrice: 999,
    categoryId: "smartphones",
    images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&h=800&fit=crop"],
    highlights: ["200MP camera", "Galaxy AI", "S Pen support"],
    specifications: [
      { label: "Display", value: "6.8-inch AMOLED" },
      { label: "Battery", value: "5000 mAh" },
      { label: "Storage", value: "256GB" },
    ],
    colors: ["Titanium Black", "Titanium Gray"],
    storageOptions: ["256GB", "512GB"],
    rating: 4.8,
    reviewCount: 270,
    featured: true,
    active: true,
    stockStatus: "in_stock",
  },
  {
    id: "airpods-pro-2",
    title: "AirPods Pro 2",
    slug: "airpods-pro-2",
    shortDescription: "Premium ANC earbuds with adaptive audio.",
    fullDescription: "AirPods Pro 2 deliver immersive sound, active noise cancellation, and seamless Apple ecosystem support.",
    brand: "Apple",
    price: 249,
    salePrice: 219,
    categoryId: "audio",
    images: ["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&h=800&fit=crop"],
    highlights: ["Active Noise Cancellation", "Adaptive Audio", "USB-C case"],
    specifications: [
      { label: "Battery", value: "Up to 6 hours" },
      { label: "Chip", value: "H2" },
      { label: "Charging", value: "USB-C" },
    ],
    colors: ["White"],
    storageOptions: [],
    rating: 4.7,
    reviewCount: 180,
    featured: false,
    active: true,
    stockStatus: "in_stock",
  },
]

export const seedReels: Array<ReelInput & { id: string }> = [
  {
    id: "reel-iphone-unboxing",
    title: "iPhone 15 Pro Max Unboxing",
    reelUrl: "https://instagram.com/reel/sample-1",
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=500&h=900&fit=crop",
    caption: "Unboxing the latest iPhone 15 Pro Max at Mobile Gallery.",
    active: true,
    featured: true,
    sortOrder: 1,
  },
  {
    id: "reel-s24-camera",
    title: "Galaxy S24 Ultra Camera Test",
    reelUrl: "https://instagram.com/reel/sample-2",
    thumbnail: "https://images.unsplash.com/photo-1591815302525-756a9bcc3425?w=500&h=900&fit=crop",
    caption: "Quick camera comparison with low light and zoom tests.",
    active: true,
    featured: false,
    sortOrder: 2,
  },
]

export const seedReviews: Array<ReviewInput & { id: string }> = [
  {
    id: "review-1",
    customerName: "Sarah Johnson",
    rating: 5,
    comment: "Fast response on WhatsApp and authentic product. Great experience.",
    sourceUrl: null,
    productId: "iphone-15-pro-max",
    featured: true,
    active: true,
  },
  {
    id: "review-2",
    customerName: "Michael Chen",
    rating: 5,
    comment: "Smooth purchase process and very good pricing.",
    sourceUrl: null,
    productId: "galaxy-s24-ultra",
    featured: true,
    active: true,
  },
  {
    id: "review-3",
    customerName: "Emily Davis",
    rating: 4,
    comment: "Excellent packaging and quick delivery.",
    sourceUrl: null,
    productId: "airpods-pro-2",
    featured: false,
    active: true,
  },
]
